== Unit 10 Recursion

하나 이상의 유한한 수가 도메인에 속하며, 하나 이상의 규칙이 도메인의
하나 이상의 요소에서 새로운 도메인 요소를 얻을 수 있게 한다.

(도메인 : 일반적인 의미는 ’*데이터 타입과 길이, 포멧 등이 같은 값의
집합)*

귀납적으로 정의된 도메인과 재귀

모든 재귀 메서드는 재귀를 시뮬레이션하기 위해 특정 데이터 구조인 스택을
사용하여 반복적으로 구현할 수 있다.

=== Run-time memory management

Java bytecode

* 클래스가 JVM에 로드될 때 실행 시간에 결정
* 각 메서드의 크기는 컴파일 시간에 고정

Heap : 객체를 포함하는 메모리의 일부

* 실행 중에 동적으로 커지고 축소한다.
* 각 객체는 다른 객체와 독립적으로 할당 및 해제된다.

Stack of Activation Records : 메서드 내에서 로컬 변수 및 매개변수를 위한
메모리의 일부

* 실행 중에 동적으로 커지고 축소한다.
* 스택 형태로 관리되며 후입선출로 관리된다.

=== Heap management and garbage collection

어떠한 변수도 클래스 깨체를 가리키지 않을 때, 객체는 더 이상 접근할 수
없으며, 이 시점에서 가비지 컬렉터가 동작하여 해당 객체의 메모리를
해제하고 회수한다. —> 자동으로 메모리 관리가 이루어짐

=== Stack of activation records

LIFO는 스택에 들어간 마지막 요소가 현재 스택에 있는 요소 중 가장 먼저
나가는 것

메서드 호출마다 새로운 activation records가 스택의 맨 위에 생성되고
메서드 활성화가 끝나면 스택에서 제거

activation records : 로컬 변수를 위한 메모리 위치가 있는 경우,

메서드 호출의 반환 값이 있는 경우,

호출 메서드에서 실행할 다음 문장의 주소를 포함

메서드가 정적 메서드가 아닌 경우 호출 객체에 대한 참조를 포함

.스크린샷 2023-10-01 오후 9.19.20.png
image::https://prod-files-secure.s3.us-west-2.amazonaws.com/30914778-8bfa-404a-8db1-10f28062c17e/a88a0806-9232-463a-a77c-e5a5a7fe5e76/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA_2023-10-01_%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE_9.19.20.png[스크린샷
2023-10-01 오후 9.19.20.png]

[arabic]
. main : m0 - m1 - m2 - m3 - m4 - return =⇒ A(vm)
. A : a0 - a1 - a2 - a3 - return =⇒ B(pa * 2)
. B : b0 - return

.스크린샷 2023-10-01 오후 9.24.57.png
image::https://prod-files-secure.s3.us-west-2.amazonaws.com/30914778-8bfa-404a-8db1-10f28062c17e/144c8d40-572b-4002-b91f-91dc57e937c2/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA_2023-10-01_%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE_9.24.57.png[스크린샷
2023-10-01 오후 9.24.57.png]

PC(Program Counter)는 현재 실행 중인 프로그램의 다음 실행할 명령어 또는
다음 실행 위치를 가리키는 레지스터 또는 값 + 프로그램의 명령어를
순차적으로 실행하는 데 사용되며 프로그램의 제어 흐름을 관리

호출된 메서드의 현재 활성화를 위한 AR(Activation Record)이 생성.

AR이 포함된 부분

* 형식 매개변수를 위한 메모리 위치: pa 매개변수
* 로컬 변수를 위한 메모리 위치: va 매개변수
* 반환 값을 위한 메모리 위치: RV
* 반환 주소를 위한 메모리 위치: RA

=== Evolution of the stack of ARs in the case of recursive methods

재귀 메서드의 경우, AR(Activation Record) 스택과 프로그램 카운터의 진화
방식은 비재귀 메서드와 정확히 동일하다.

—> 재귀 메서드의 호출은 AR 스택에 새로운 활성화를 추가하고, 재귀 호출이
완료되면 해당 활성화를 제거한다. 이 점은 비재귀 메서드와 동일한 스택 및
프로그램 카운터 진화 방식이다.

다양한 재귀 활성화에 대해 서로 다른 AR(Activation Record)이 스택에
생성된다.

다양한 재귀 활성화와 관련된 Java 바이트 코드는 항상 동일하다. 즉, 메서드
recursive의 바이트 코드와 동일. 따라서 다양한 재귀 활성화에 대한 AR에
저장된 반환 주소는 항상 동일하다.

=== palindrome string

문자열의 팰린드롬(palindrome): 만약 문자열을 왼쪽에서 오른쪽으로 읽을
때와 오른쪽에서 왼쪽으로 읽을 때 동일하다면 팰린드롬이라고 한다.

=== symmetric sequence of integers

정수 시퀀스가 중앙 위치에 있는 단일 0을 제외하고 모두 양수인 경우 해당
시퀀스를 대칭(symmetric)이라고 한다.

=== Hanoi’s Top

.스크린샷 2023-10-01 오후 10.42.10.png
image::https://prod-files-secure.s3.us-west-2.amazonaws.com/30914778-8bfa-404a-8db1-10f28062c17e/d53e7f9f-dfe6-4198-861c-415d17b53512/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA_2023-10-01_%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE_10.42.10.png[스크린샷
2023-10-01 오후 10.42.10.png]

[arabic]
. n > 1개의 디스크를 지원 1에서 지원 2로 이동하려면 지원 3을 보조
지원으로 사용
. 지원 1에서 지원 2로 n - 1개의 디스크를 이동 (n 번째 디스크는 움직이지
않음).
. 지원 1에서 지원 2로 n 번째 디스크를 이동
. 지원 3에서 지원 2로 n - 1개의 디스크를 이동 (n 번째 디스크는 움직이지
않음).

=== Traversal of a moor

*: 육지

o: 해상

육지를 통해 경로를 건너가야 한다.

.스크린샷 2023-10-02 오후 3.28.31.png
image::https://prod-files-secure.s3.us-west-2.amazonaws.com/30914778-8bfa-404a-8db1-10f28062c17e/18bc0ee2-afdf-46e9-9187-a30b93beb44a/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA_2023-10-02_%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE_3.28.31.png[스크린샷
2023-10-02 오후 3.28.31.png]

traversal(횡단)은 모어를 횡단하는 경로를 의미한다.

모어의 각 영역은 hr, ci라는 좌표 쌍으로 식별한다.

즉, R X C 정사각형 구역에서, 모어를 왼쪽(열 0)에서 오른쪽(열 C - 1)으로
횡단하는 연속적인 인접한 육지 영역의 시퀀스이며, 각 단계에서는
오른쪽으로 이동하는데, 열 c의 영역에서 열 c + 1의 영역으로 이동한다.

.스크린샷 2023-10-02 오후 5.44.47.png
image::https://prod-files-secure.s3.us-west-2.amazonaws.com/30914778-8bfa-404a-8db1-10f28062c17e/e94ef7b5-812e-45ae-8678-03006aceabf1/%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA_2023-10-02_%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE_5.44.47.png[스크린샷
2023-10-02 오후 5.44.47.png]

Traversal of a moor 알고리즘

[arabic]
. 첫 번째 단계에서는 첫 번째 열(column)에 있는 육지 영역을 찾고, 육지
영역에서 시작한다.
. 일반적인 재귀 단계에서 hr, ci 위치에 있다.

* 만약 해당 위치가 육지 영역이라면, 계속해서 다음 위치(hr - 1, c + 1i,
hr, c + 1i, hr + 1, c + 1i)를 재귀적으로 탐색한다.
* 만약 해당 위치가 물 영역이라면, 우리는 더 이상 진행할 수 없으며 해당
위치에서의 탐색이 종료된다.

[arabic]
. 전체 탐색은 마지막 열(column)에 있는 영역(c가 C - 1인)에 도달하고 해당
영역이 육지인 경우면 성공적으로 종료된다.
